using Microsoft.EntityFrameworkCore.Migrations;

namespace TestDedalus.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    CountryId = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: false),
                    CountryName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.CountryId);
                });

            migrationBuilder.CreateTable(
                name: "Capitals",
                columns: table => new
                {
                    CapitalId = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: false),
                    CapitalName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CountryId = table.Column<string>(type: "nvarchar(2)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Capitals", x => x.CapitalId);
                    table.ForeignKey(
                        name: "FK_Capitals_Countries_CountryId",
                        column: x => x.CountryId,
                        principalTable: "Countries",
                        principalColumn: "CountryId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "CountryId", "CountryName" },
                values: new object[,]
                {
                    { "AX", "Åland Islands" },
                    { "NE", "Niger" },
                    { "NG", "Nigeria" },
                    { "NU", "Niue" },
                    { "NF", "Norfolk Island" },
                    { "KP", "North Korea" },
                    { "MP", "Northern Mariana Islands" },
                    { "NO", "Norway" },
                    { "OM", "Oman" },
                    { "PK", "Pakistan" },
                    { "PW", "Palau" },
                    { "PS", "Palestinian Territory, Occupied" },
                    { "PA", "Panama" },
                    { "NI", "Nicaragua" },
                    { "PG", "Papua-New Guinea" },
                    { "PE", "Peru" },
                    { "PH", "Philippines" },
                    { "PN", "Pitcairn" },
                    { "PL", "Poland" },
                    { "PT", "Portugal" },
                    { "PR", "Puerto Rico" },
                    { "QA", "Quatar" },
                    { "RE", "Reunion" },
                    { "RO", "Romania" },
                    { "RU", "Russian Federation" },
                    { "RW", "Rwanda" },
                    { "BL", "Saint Barthélemy" },
                    { "PY", "Paraguay" },
                    { "NZ", "New Zealand" },
                    { "NC", "New Caledonia" },
                    { "AN", "Netherlands Antilles" },
                    { "MO", "Macao" },
                    { "MK", "Macedonia (former YR)" },
                    { "MG", "Madagascar" },
                    { "MW", "Malawi" },
                    { "MY", "Malaysia" },
                    { "MV", "Maldives (Maladive Ilands)" },
                    { "ML", "Mali" },
                    { "MT", "Malta" },
                    { "MH", "Marshall Islands" },
                    { "MQ", "Martinique" },
                    { "MR", "Mauritania" }
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "CountryId", "CountryName" },
                values: new object[,]
                {
                    { "MU", "Mauritius" },
                    { "YT", "Mayotte" },
                    { "MX", "Mexico" },
                    { "FM", "Micronesia (Federa States of)" },
                    { "MD", "Moldova, Republic of" },
                    { "MC", "Monaco" },
                    { "MN", "Mongolia" },
                    { "ME", "Montenegro" },
                    { "MS", "Montserrat" },
                    { "MA", "Morocco" },
                    { "MZ", "Mozambique" },
                    { "MM", "Myanmar (Burma)" },
                    { "NA", "Namibia" },
                    { "NR", "Nauru" },
                    { "NP", "Nepal" },
                    { "NL", "Netherlands" },
                    { "SH", "Saint Helena, Ascension and Tristan da Cunha" },
                    { "PM", "Saint Pierre And Micquelon" },
                    { "SM", "San Marino" },
                    { "ST", "Sao Tome & Principe" },
                    { "TG", "Togo" },
                    { "TK", "Tokelau" },
                    { "TO", "Tonga" },
                    { "TT", "Trinidad & Tobago" },
                    { "TN", "Tunisia" },
                    { "TR", "Turkey" },
                    { "TM", "Turkmenistan" },
                    { "TC", "Turks And Caicos Islands" },
                    { "TV", "Tuvalu" },
                    { "UG", "Uganda" },
                    { "UA", "Ukraine" },
                    { "AE", "United Arab Emirates" },
                    { "GB", "United Kingdom" },
                    { "US", "United States" },
                    { "UM", "United States Minor Outlying Islands" },
                    { "UY", "Uruguay" },
                    { "UZ", "Uzbekistan" },
                    { "VU", "Vanuatu" },
                    { "VA", "Vatican City" },
                    { "VE", "Venezuela" },
                    { "VN", "Vietnam" },
                    { "VG", "Virgin Islands, British" }
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "CountryId", "CountryName" },
                values: new object[,]
                {
                    { "VI", "Virgin Islands, U.S." },
                    { "WF", "Wallis And Futuna" },
                    { "EH", "Western Sahara" },
                    { "WS", "Western Samoa" },
                    { "YE", "Yemen" },
                    { "TL", "Timor-Leste" },
                    { "LU", "Luxembourg" },
                    { "TH", "Thailand" },
                    { "TJ", "Tajikistan" },
                    { "SA", "Saudi Arabia" },
                    { "SN", "Senegal" },
                    { "RS", "Serbia" },
                    { "SC", "Seychelles" },
                    { "SL", "Sierra Leone" },
                    { "SG", "Singapore" },
                    { "SX", "Sint-Maarten" },
                    { "SK", "Slovakia" },
                    { "SI", "Slovenia" },
                    { "SB", "Solomon Islands" },
                    { "SO", "Somalia" },
                    { "ZA", "South Africa" },
                    { "GS", "South Georgia & South Sandwich Islands" },
                    { "KR", "South Korea" },
                    { "ES", "Spain" },
                    { "LK", "Sri Lanka" },
                    { "KN", "St. Kitts & Nevis" },
                    { "LC", "St. Lucia" },
                    { "VC", "St. Vincent & Grenadines" },
                    { "SD", "Sudan" },
                    { "SR", "Suriname" },
                    { "SJ", "Svalbard And Jan Mayen" },
                    { "SZ", "Swaziland" },
                    { "SE", "Sweden" },
                    { "CH", "Switzerland" },
                    { "SY", "Syrian Arab Republic" },
                    { "TW", "Taiwan" },
                    { "TZ", "Tanzania" },
                    { "LT", "Lithuania" },
                    { "LI", "Liechtenstein" },
                    { "LY", "Libyan Arab Jamahiriya" },
                    { "IO", "Britsh Indian Ocean Territory" },
                    { "BN", "Brunei-Darussalam" }
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "CountryId", "CountryName" },
                values: new object[,]
                {
                    { "BG", "Bulgaria" },
                    { "BF", "Burkina Faso" },
                    { "BI", "Burundi" },
                    { "CI", "Côte D'Ivoire (Ivory Coast)" },
                    { "KH", "Cambodia" },
                    { "CM", "Cameroon" },
                    { "CA", "Canada" },
                    { "CV", "Cape Verde" },
                    { "KY", "Cayman Islands" },
                    { "CF", "Central African Republic" },
                    { "TD", "Chad" },
                    { "CL", "Chile" },
                    { "CN", "China" },
                    { "CX", "Chrismas Island" },
                    { "CC", "Cocos (Keeling) Islands" },
                    { "MF", "Collectivity of Saint Martin" },
                    { "CO", "Colombia" },
                    { "KM", "Comoros" },
                    { "CG", "Congo" },
                    { "CD", "Congo, Democratic Republic" },
                    { "CK", "Cook Islands" },
                    { "CR", "Costa Rica" },
                    { "HR", "Croatia" },
                    { "CU", "Cuba" },
                    { "CW", "Curaçao" },
                    { "BR", "Brazil" },
                    { "CY", "Cyprus" },
                    { "BV", "Bouvet Island" },
                    { "BA", "Bosnia & Herzegovina" },
                    { "AF", "Afghanistan" },
                    { "AL", "Albania" },
                    { "DZ", "Algeria" },
                    { "AS", "American Samoa" },
                    { "AD", "Andorra" },
                    { "AO", "Angola" },
                    { "AI", "Anguilla" },
                    { "AQ", "Antarctica" },
                    { "AG", "Antigua & Barbuda" },
                    { "AR", "Argentina" },
                    { "AM", "Armenia" },
                    { "AW", "Aruba" },
                    { "AU", "Australia" }
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "CountryId", "CountryName" },
                values: new object[,]
                {
                    { "AT", "Austria" },
                    { "AZ", "Azerbaijan" },
                    { "BS", "Bahamas" },
                    { "BH", "Bahrain" },
                    { "BD", "Bangladesh" },
                    { "BB", "Barbados" },
                    { "BY", "Belarus" },
                    { "BE", "Belgium" },
                    { "BZ", "Belize" },
                    { "BJ", "Benin" },
                    { "BM", "Bermuda" },
                    { "BT", "Bhutan" },
                    { "BO", "Bolivia" },
                    { "BQ", "Bonaire, Sint Eustatius and Saba" },
                    { "BW", "Botswana" },
                    { "ZM", "Zambia" },
                    { "CZ", "Czech Republic" },
                    { "DJ", "Djibouti" },
                    { "GY", "Guyana" },
                    { "HT", "Haiti" },
                    { "HM", "Heard Island And McDonald Islands" },
                    { "HN", "Honduras" },
                    { "HK", "Hong Kong" },
                    { "HU", "Hungary" },
                    { "IS", "Iceland" },
                    { "IN", "India" },
                    { "ID", "Indonesia" },
                    { "IR", "Iran" },
                    { "IQ", "Iraq" },
                    { "IE", "Ireland" },
                    { "IL", "Israel" },
                    { "IT", "Italy" },
                    { "JM", "Jamaica" },
                    { "JP", "Japan" },
                    { "JO", "Jordan" },
                    { "KZ", "Kazakhstan" },
                    { "KE", "Kenya" },
                    { "KI", "Kiribati" },
                    { "KW", "Kuwait" },
                    { "KG", "Kyrgyzstan" },
                    { "LA", "Laos" },
                    { "LV", "Latvia" }
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "CountryId", "CountryName" },
                values: new object[,]
                {
                    { "LB", "Lebanon" },
                    { "LS", "Lesotho" },
                    { "LR", "Liberia" },
                    { "GW", "Guinea-Bissau" },
                    { "DK", "Denmark" },
                    { "GN", "Guinea" },
                    { "GU", "Guam" },
                    { "DM", "Dominica" },
                    { "DO", "Dominican Republic" },
                    { "EC", "Ecuador" },
                    { "EG", "Egypt" },
                    { "SV", "El Salvador" },
                    { "GQ", "Equatorial Guinea" },
                    { "ER", "Eritrea" },
                    { "EE", "Estonia" },
                    { "ET", "Ethiopia" },
                    { "FK", "Falkand Islands (Malvinas)" },
                    { "FO", "Faroe Islands" },
                    { "FJ", "Fiji" },
                    { "FI", "Finland" },
                    { "FR", "France" },
                    { "GF", "French Guiana" },
                    { "PF", "French Polynesia" },
                    { "TF", "French Southern Territories" },
                    { "GA", "Gabon" },
                    { "GM", "Gambia" },
                    { "GE", "Georgia" },
                    { "DE", "Germany" },
                    { "GH", "Ghana" },
                    { "GI", "Gibraltar" },
                    { "GR", "Greece" },
                    { "GL", "Greenland" },
                    { "GD", "Grenada" },
                    { "GP", "Guadeloupe" },
                    { "GT", "Guatemala" },
                    { "ZW", "Zimbabwe" }
                });

            migrationBuilder.InsertData(
                table: "Capitals",
                columns: new[] { "CapitalId", "CapitalName", "CountryId" },
                values: new object[,]
                {
                    { "001", "Mariehamn", "AX" },
                    { "157", "Niamey", "NE" },
                    { "158", "Abuja", "NG" },
                    { "159", "Alofi", "NU" },
                    { "160", "Kingston", "NF" },
                    { "161", "Pyongyang", "KP" },
                    { "162", "Saipan", "MP" },
                    { "163", "Oslo", "NO" },
                    { "164", "Muscat", "OM" },
                    { "165", "Islamabad", "PK" },
                    { "166", "Koror", "PW" },
                    { "167", "East Jerusalem", "PS" },
                    { "168", "Panama", "PA" },
                    { "156", "Managua", "NI" },
                    { "169", "Port Moresby", "PG" },
                    { "171", "Lima", "PE" },
                    { "172", "Manila", "PH" },
                    { "173", "Adamstown", "PN" },
                    { "174", "Warsaw", "PL" },
                    { "175", "Lisbon", "PT" },
                    { "176", "San Juan", "PR" },
                    { "177", "Doha", "QA" },
                    { "178", "Saint-Denis", "RE" },
                    { "179", "Bucharest", "RO" },
                    { "180", "Moscow", "RU" },
                    { "181", "Kigali", "RW" },
                    { "182", "Gustavia", "BL" },
                    { "170", "Asuncion", "PY" },
                    { "155", "Wellington", "NZ" },
                    { "154", "Nouméa", "NC" },
                    { "153", "Willemstad", "AN" },
                    { "126", "Macao", "MO" },
                    { "127", "Skopje", "MK" },
                    { "128", "Antananarivo", "MG" },
                    { "129", "Lilongwe", "MW" },
                    { "130", "Kuala Lumpur", "MY" },
                    { "131", "Male", "MV" },
                    { "132", "Bamako", "ML" },
                    { "133", "Valetta", "MT" },
                    { "134", "Majuro", "MH" },
                    { "135", "Fort-de-France", "MQ" },
                    { "136", "Novakchott", "MR" }
                });

            migrationBuilder.InsertData(
                table: "Capitals",
                columns: new[] { "CapitalId", "CapitalName", "CountryId" },
                values: new object[,]
                {
                    { "137", "Port Louis", "MU" },
                    { "138", "Mamoudzou", "YT" },
                    { "139", "Mexico City", "MX" },
                    { "140", "Kolonia", "FM" },
                    { "141", "Kishinev", "MD" },
                    { "142", "Monaco", "MC" },
                    { "143", "Ulan Bator", "MN" },
                    { "144", "Podgorica", "ME" },
                    { "145", "Plymouth", "MS" },
                    { "146", "Rabat", "MA" },
                    { "147", "Maputo", "MZ" },
                    { "148", "Rangoon", "MM" },
                    { "149", "Windhoek", "NA" },
                    { "150", "Nauru", "NR" },
                    { "151", "Katmandu", "NP" },
                    { "152", "Amsterdam", "NL" },
                    { "183", "Jamestown", "SH" },
                    { "184", "Saint Pierre", "PM" },
                    { "185", "San Marino", "SM" },
                    { "186", "Sao Tome", "ST" },
                    { "218", "Lome", "TG" },
                    { "219", "-", "TK" },
                    { "220", "Nuku'alofa", "TO" },
                    { "221", "Port of Spain", "TT" },
                    { "222", "Tunis", "TN" },
                    { "223", "Ankara", "TR" },
                    { "224", "Ashkhabad", "TM" },
                    { "225", "Cockburn Town, Grand Turk", "TC" },
                    { "226", "Funafuti", "TV" },
                    { "227", "Kampala", "UG" },
                    { "228", "Kiev", "UA" },
                    { "229", "Abu Dhabi", "AE" },
                    { "230", "London", "GB" },
                    { "231", "Washington", "US" },
                    { "232", "-", "UM" },
                    { "233", "Montevideo", "UY" },
                    { "234", "Tashkent", "UZ" },
                    { "235", "Port Vila", "VU" },
                    { "236", "Vatican City", "VA" },
                    { "237", "Caracas", "VE" },
                    { "238", "Hanoi", "VN" },
                    { "239", "Road Town", "VG" }
                });

            migrationBuilder.InsertData(
                table: "Capitals",
                columns: new[] { "CapitalId", "CapitalName", "CountryId" },
                values: new object[,]
                {
                    { "240", "Charlotte Amalie", "VI" },
                    { "241", "Mata-Utu", "WF" },
                    { "242", "Laâyoune", "EH" },
                    { "243", "Apia", "WS" },
                    { "244", "Sanaa", "YE" },
                    { "217", "Dili", "TL" },
                    { "125", "Luxembourg", "LU" },
                    { "216", "Bangkok", "TH" },
                    { "214", "Dushanbe", "TJ" },
                    { "187", "Riyadh", "SA" },
                    { "188", "Dakar", "SN" },
                    { "189", "Belgrade", "RS" },
                    { "190", "Victoria", "SC" },
                    { "191", "Freetown", "SL" },
                    { "192", "Singapore", "SG" },
                    { "193", "Philipsburg", "SX" },
                    { "194", "Bratislava", "SK" },
                    { "195", "Ljubljana", "SI" },
                    { "196", "Honiara", "SB" },
                    { "197", "Mogadishu", "SO" },
                    { "198", "Cape Town", "ZA" },
                    { "199", "Grytviken", "GS" },
                    { "200", "Seoul", "KR" },
                    { "201", "Madrid", "ES" },
                    { "202", "Colombo", "LK" },
                    { "203", "Basseterre", "KN" },
                    { "204", "Castries", "LC" },
                    { "205", "Kingstown", "VC" },
                    { "206", "Khartoum", "SD" },
                    { "207", "Paramaribo", "SR" },
                    { "208", "Svalbard And Jan Mayen", "SJ" },
                    { "209", "Mbabane", "SZ" },
                    { "210", "Stockholm", "SE" },
                    { "211", "Bern", "CH" },
                    { "212", "Damascus", "SY" },
                    { "213", "Taipei", "TW" },
                    { "215", "Dar es Salaam", "TZ" },
                    { "124", "Vilnius", "LT" },
                    { "123", "Vaduz", "LI" },
                    { "122", "Tripoli", "LY" },
                    { "033", "Diego Garcia", "IO" },
                    { "034", "Bandar Seri Begawan", "BN" }
                });

            migrationBuilder.InsertData(
                table: "Capitals",
                columns: new[] { "CapitalId", "CapitalName", "CountryId" },
                values: new object[,]
                {
                    { "035", "Sofia", "BG" },
                    { "036", "Ouagadougou", "BF" },
                    { "037", "Bujumbura", "BI" },
                    { "038", "Yamoussoukro", "CI" },
                    { "039", "Phnom Penh", "KH" },
                    { "040", "Yaounde", "CM" },
                    { "041", "Ottawa", "CA" },
                    { "042", "Cidade de Praia", "CV" },
                    { "043", "George Town", "KY" },
                    { "044", "Bangui", "CF" },
                    { "045", "N'Djamena", "TD" },
                    { "046", "Santiago", "CL" },
                    { "047", "Beijing", "CN" },
                    { "048", "Flying Fish Cove", "CX" },
                    { "049", "West Island", "CC" },
                    { "050", "Marigot", "MF" },
                    { "051", "Bogota", "CO" },
                    { "052", "Moroni", "KM" },
                    { "053", "Brazzerville", "CG" },
                    { "054", "Kinshasha", "CD" },
                    { "055", "Avarua", "CK" },
                    { "056", "San Jose", "CR" },
                    { "057", "Zagreb", "HR" },
                    { "058", "Havana", "CU" },
                    { "059", "Willemstad", "CW" },
                    { "032", "Brasilia", "BR" },
                    { "060", "Nicosia", "CY" },
                    { "031", "None", "BV" },
                    { "029", "Sarajevo", "BA" },
                    { "002", "Kabul", "AF" },
                    { "003", "Tirana", "AL" },
                    { "004", "Algiers", "DZ" },
                    { "005", "Pago Pago", "AS" },
                    { "006", "Andorra La Ville", "AD" },
                    { "007", "Luanda", "AO" },
                    { "008", "The Valley", "AI" },
                    { "009", "None", "AQ" },
                    { "010", "St. John's", "AG" },
                    { "011", "Buenos Aires", "AR" },
                    { "012", "Yerevan", "AM" },
                    { "013", "Oranjestad", "AW" },
                    { "014", "Canberra", "AU" }
                });

            migrationBuilder.InsertData(
                table: "Capitals",
                columns: new[] { "CapitalId", "CapitalName", "CountryId" },
                values: new object[,]
                {
                    { "015", "Vienna", "AT" },
                    { "016", "Baku", "AZ" },
                    { "017", "Nassau", "BS" },
                    { "018", "Manama", "BH" },
                    { "019", "Dhaka", "BD" },
                    { "020", "Bridgetown", "BB" },
                    { "021", "Minsk", "BY" },
                    { "022", "Brussels", "BE" },
                    { "023", "Belmopan", "BZ" },
                    { "024", "Porto-Novo", "BJ" },
                    { "025", "Hamilton", "BM" },
                    { "026", "Timphu", "BT" },
                    { "027", "La Paz", "BO" },
                    { "028", "-", "BQ" },
                    { "030", "Gaborone", "BW" },
                    { "245", "Lusaka", "ZM" },
                    { "061", "Prague", "CZ" },
                    { "063", "Djibouti", "DJ" },
                    { "095", "Georgetown", "GY" },
                    { "096", "Port-Au-Prince", "HT" },
                    { "097", "-", "HM" },
                    { "098", "Tegucigalpa", "HN" },
                    { "099", "Hong Kong", "HK" },
                    { "100", "Budapest", "HU" },
                    { "101", "Reykjavik", "IS" },
                    { "102", "New Delhi", "IN" },
                    { "103", "Jakarta", "ID" },
                    { "104", "Tehran", "IR" },
                    { "105", "Baghdad", "IQ" },
                    { "106", "Dublin", "IE" },
                    { "107", "Jerusalem", "IL" },
                    { "108", "Rome", "IT" },
                    { "109", "Kingston", "JM" },
                    { "110", "Tokyo", "JP" },
                    { "111", "Amman", "JO" },
                    { "112", "Almaty", "KZ" },
                    { "113", "Nairobi", "KE" },
                    { "114", "Tarawa", "KI" },
                    { "115", "Kuwait", "KW" },
                    { "116", "Bishkek", "KG" },
                    { "117", "Vientiane", "LA" },
                    { "118", "Riga", "LV" }
                });

            migrationBuilder.InsertData(
                table: "Capitals",
                columns: new[] { "CapitalId", "CapitalName", "CountryId" },
                values: new object[,]
                {
                    { "119", "Beirut", "LB" },
                    { "120", "Masera", "LS" },
                    { "121", "Monrovia", "LR" },
                    { "094", "Bissau", "GW" },
                    { "062", "Copenhagen", "DK" },
                    { "093", "Conakry", "GN" },
                    { "091", "Hagatna (Agana)", "GU" },
                    { "064", "Roseau", "DM" },
                    { "065", "Santo Domingo", "DO" },
                    { "066", "Quito", "EC" },
                    { "067", "Cairo", "EG" },
                    { "068", "San Salvador", "SV" },
                    { "069", "Bata", "GQ" },
                    { "070", "Asmara", "ER" },
                    { "071", "Tallinn", "EE" },
                    { "072", "Addis Ababa", "ET" },
                    { "073", "Port Stanley", "FK" },
                    { "074", "Torshavn", "FO" },
                    { "075", "Suva", "FJ" },
                    { "076", "Helsinki", "FI" },
                    { "077", "Paris", "FR" },
                    { "078", "Cayenne", "GF" },
                    { "079", "Papeete", "PF" },
                    { "080", "-", "TF" },
                    { "081", "Libreville", "GA" },
                    { "082", "Banjul", "GM" },
                    { "083", "Tbilisi", "GE" },
                    { "084", "Berlin", "DE" },
                    { "085", "Accra", "GH" },
                    { "086", "Gibraltar", "GI" },
                    { "087", "Athens", "GR" },
                    { "088", "Nuuk", "GL" },
                    { "089", "St. George's", "GD" },
                    { "090", "Basse-Terre", "GP" },
                    { "092", "Guatemala", "GT" },
                    { "246", "Harare", "ZW" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Capitals_CountryId",
                table: "Capitals",
                column: "CountryId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Capitals");

            migrationBuilder.DropTable(
                name: "Countries");
        }
    }
}
